FROM alpine:latest
LABEL description="Cloud Game Server Container"
RUN apk add --no-cache curl bash
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 7777
ENTRYPOINT ["/entrypoint.sh"]