FROM nginx:alpine
LABEL maintainer="cloud-admin@tp.local"
LABEL description="Cloud Reverse Proxy - Nginx personnalisé"

RUN apk update && apk add --no-cache curl && rm -rf /var/cache/apk/*

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost/ || exit 1
CMD ["nginx", "-g", "daemon off;"]  